# Generated by Django 3.1.1 on 2020-09-07 23:14

import datetime
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(choices=[('Prof.', 'Prof.'), ('PhD', 'PhD'), ('MSc', 'MSc'), ('Eng.', 'Eng.'), ('---', '---')], max_length=100, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('10 x 10 x 10', '10 x 10 x 10'), ('15 x 15 x 15', '15 x 15 x 15'), ('10 x 10 x 50', '10 x 10 x 50'), ('15 x 15 x 70', '15 x 15 x 70')], max_length=100, null=True)),
                ('modification', models.CharField(choices=[('steel fibers', 'steel fibers'), ('glass fibers', 'glass fibers'), ('polypropylene fibers', 'polypropylene fibers'), ('kaoline', 'kaoline'), ('zeolite', 'zeolite')], max_length=100, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('date_of_production', models.DateField(default=datetime.datetime(2020, 9, 7, 23, 14, 32, 5064))),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In Production', 'In Production'), ('In Research', 'In Research'), ('Tested', 'Tested')], max_length=32, null=True)),
            ],
        ),
    ]
