# Generated by Django 3.1.1 on 2020-09-09 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200907_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.executor'),
        ),
        migrations.AddField(
            model_name='test',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_of_production',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 16, 26, 49, 21457)),
        ),
    ]
