# Generated by Django 3.1.1 on 2020-09-09 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200909_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_of_production',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 16, 31, 2, 451008)),
        ),
        migrations.AddField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
