# Generated by Django 3.1.1 on 2020-09-09 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200909_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='tags',
        ),
        migrations.AddField(
            model_name='sample',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_of_production',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 16, 33, 7, 563586)),
        ),
    ]
