# Generated by Django 3.1.1 on 2020-09-13 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200909_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date_of_production',
            field=models.DateField(default=datetime.datetime(2020, 9, 13, 10, 5, 54, 141290)),
        ),
    ]
