# Generated by Django 3.1.1 on 2020-09-13 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200913_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_of_production',
            field=models.DateField(default=datetime.datetime(2020, 9, 13, 12, 42, 25, 707457)),
        ),
    ]
